# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba43d4b30f52f2a80f35bd906edcc897ae3a5ded190ef73a4d850ffa0f21ecae809e3073805f178940df01653b04f4615540f370cebfd7524174ea91fa3037d8

test:
  secret_key_base: fb9bbb631ef6fa966ba48b18109bf033450f531130b2baf4449f073c45c7d152cc20359eb1befbdac687200ec6ccdf4728caec598291c3643088dc841a20c219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
